"""Render governance rubrics into a reviewer prompt block.

VERBATIM COPY of ``format_rubric_context`` and its helpers from
``codeguard/prompts.py`` in the GuardSpine monorepo, which is the canonical
implementation and the one the spreadsheet lane uses.

Why a copy. The action is a separate repository and cannot import codeguard:
the backend installs that package from local source, and the copy published to
PyPI is stale (0.1.3 against 0.3.0 in-tree). Publishing it properly is the
durable fix and is tracked separately.

Why a copy is dangerous, and what makes this one safe. A private
reimplementation of shared logic is precisely what produced the v2.2.0
failure: a bespoke canonical-JSON writer drifted from the shared one and every
signed evidence bundle was rejected, undetected, for two releases. The
difference here is that both implementations render a shared golden vector
(guardspine-spec/fixtures/golden-vectors/rubric-prompt-context.json) and a
test in each repo fails the moment their bytes differ. Do not edit this file
without updating the canonical one and the vector together.

The block is what makes a rubric more than a name to a reviewer model: each
rule's id, severity and intent, so a finding can cite the control it hit.
"""

# Rubric text reaches reviewer prompts and custom rubrics are org-editable:
# strip angle brackets so a description can never close the
# <governance_rubrics> block or smuggle new instruction tags, and cap
# length so one rule cannot flood the prompt.
_MAX_RUBRIC_RULES = 60
_MAX_FIELD_CHARS = 200
_MAX_PACKS = 20
_MAX_BLOCK_CHARS = 20000


def _rubric_field(obj, field, default=""):
    """Read a raw field from a Rubric/Rule model OR a plain dict (backend
    custom rubrics arrive as parsed YAML dicts). No sanitization -- callers
    that render free text into the prompt use _rubric_text()."""
    if isinstance(obj, dict):
        return obj.get(field, default)
    return getattr(obj, field, default)


def _rubric_text(obj, field, default=""):
    """Free-text rubric field rendered into the reviewer prompt. Custom
    rubrics are org-editable, so neutralize prompt-injection surface:
    strip angle brackets (no closing our block / opening instruction tags),
    collapse newlines to spaces (no multi-line fake-instruction blocks),
    and cap length. id/severity are NOT run through this -- they are
    constrained slugs/enums and are cited verbatim in findings."""
    value = _rubric_field(obj, field, default)
    if not isinstance(value, str):
        return value
    value = value.replace("<", "").replace(">", "")
    value = " ".join(value.split())  # collapse all whitespace incl. newlines
    if len(value) > _MAX_FIELD_CHARS:
        value = value[:_MAX_FIELD_CHARS] + "..."
    return value


def format_rubric_context(rubric) -> str:
    """Render the active governance rubric(s) into a prompt block.

    The regex evaluator and the LLM reviewers must see the SAME rules:
    the block carries each rule's article-cited id, severity, and intent
    so model findings can name the legal/control requirement they hit.
    Accepts a single rubric, a list of rubrics, or dict-shaped rubrics.
    Returns "" when no rubric is active (prompts stay byte-identical).
    """
    if rubric is None:
        return ""
    rubrics = rubric if isinstance(rubric, (list, tuple)) else [rubric]

    active_packs = [p for p in rubrics if p is not None]
    packs_omitted = max(0, len(active_packs) - _MAX_PACKS)
    active_packs = active_packs[:_MAX_PACKS]

    sections: list[str] = []
    rendered = 0
    omitted = 0
    for pack in active_packs:
        rules = [
            r for r in _rubric_field(pack, "rules", [])
            if _rubric_field(r, "enabled", True)
        ]
        if not rules:
            continue
        name = _rubric_text(pack, "name", "unnamed")
        version = _rubric_text(pack, "version", "?")
        sections.append(f"Active rubric pack: {name} (v{version})")
        for rule in rules:
            if rendered >= _MAX_RUBRIC_RULES:
                omitted += 1
                continue
            rendered += 1
            # id + severity cited verbatim (constrained slugs/enums);
            # name + description sanitized as untrusted free text.
            sections.append(
                f"- {_rubric_field(rule, 'id')} [{_rubric_field(rule, 'severity')}] "
                f"{_rubric_text(rule, 'name')}: {_rubric_text(rule, 'description')}"
            )
        sections.append("")
    if omitted or packs_omitted:
        note = []
        if omitted:
            note.append(f"{omitted} more enabled rules")
        if packs_omitted:
            note.append(f"{packs_omitted} more enabled packs")
        sections.append(
            f"({' and '.join(note)} not shown -- caps {_MAX_RUBRIC_RULES} rules / "
            f"{_MAX_PACKS} packs; the regex evaluator still enforces all of them)"
        )
        sections.append("")
    if not sections:
        return ""

    lines = [
        "<governance_rubrics>",
        "These are the governance controls this organization enforces on",
        "changes. Flag any change that violates or weakens one, and cite",
        "the rule id in your finding's category or description.",
        "",
        *sections,
    ]
    lines[-1] = "</governance_rubrics>"  # replace trailing blank
    block = "\n".join(lines)
    # Hard global ceiling: no rubric config can unbound the prompt. Truncate
    # inside the block and re-close the tag so it stays well-formed.
    if len(block) > _MAX_BLOCK_CHARS:
        keep = _MAX_BLOCK_CHARS - len("\n... (truncated)\n</governance_rubrics>")
        block = block[:keep] + "\n... (truncated)\n</governance_rubrics>"
    return block
